image: vbeffara/simulations

cache:
  key: "simulations"
  paths:
    - .ccache

cmake:
  stage: build
  script:
    - export PATH=/usr/lib/ccache:$PATH
    - export CCACHE_DIR=$PWD/.ccache
    - mkdir -p build/cov
    - cd build
    - cmake .. -G Ninja -DCOV=1
    - ninja
  artifacts:
    paths:
      - build/

unittests:
  stage: test
  script:
    - Xvfb :4 &
    - export DISPLAY=:4
    - lcov -z -d build
    - ./build/tests/tests -r short -l error -x
    - lcov -c -d build -d libvb -o build/cov/cov.info --no-external -q
    - codecov -t $CODECOV_TOKEN
    - coveralls-lcov -t $COVERALLS_TOKEN build/cov/cov.info
