image: ubuntu:latest

before_script:
  - apt-get update -qq
  - apt-get install -y -qq libcairo2-dev libfltk1.3-dev libfftw3-dev libfplll-dev libgmp-dev libmpfr-dev libpng++-dev
  - apt-get install -y -qq cmake gcc g++ libboost-all-dev git ninja-build libyaml-cpp-dev libcln-dev libgsl-dev ccache

cache:
  paths:
    - .ccache

cmake:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja
    - cd ..
    - Xvfb :4 &
    - export DISPLAY=:4
    # - lcov -z -d build
    - ./build/tests/tests -r short -l error -x
    # - lcov -c -d build -d libvb -o build/cov/cov.info --gcov-tool gcov-5 --no-external -q || true
    # - codecov --gcov-exec gcov-5
    # - coveralls-lcov build/cov/cov.info
    - du -h .ccache
