image: kaskada/cmake-gcc5

before_script:
  - apt-get update -qq
  - apt-get install -y -qq libcairo2-dev libfltk1.3-dev libfftw3-dev libfplll-dev libgmp-dev libmpfr-dev libpng++-dev ninja-build libyaml-cpp-dev

cmake:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake .. -G Ninja
    - ninja
    - cd ..
    - ./build/tests/tests -r short -l error -x
