language: cpp
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - lcov
      - libboost-all-dev
      - libcln-dev
      - libfftw3-dev
      - libfltk1.3-dev
      - libfplll-dev
      - libmpfr-dev
      - libpng++-dev
      - libxinerama-dev
      - libyaml-cpp-dev
      - ninja-build

script:
  - set -e
  - export CC=gcc-5
  - export CXX=g++-5
  - gem install coveralls-lcov
  - sudo pip install codecov
  - mkdir -p build/cov
  - cd build
  - cmake .. -G Ninja -DCOV=1
  - ninja
  - cd ..
  - Xvfb :4 &
  - export DISPLAY=:4
  - lcov -z -d build
  - ./build/tests/tests -r short -l error -x
  - lcov -c -d build -d libvb -o build/cov/cov.info --gcov-tool gcov-5 --no-external -q || true
  - codecov --gcov-exec gcov-5
  - coveralls-lcov --repo-token wehYYgnFXUtYuVoHkuAZHLd5mdhtN6tyg build/cov/cov.info
